version: '3'

services:
  backstage:
    image: backstage:latest
    env_file:
      - .env
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      BACKEND_SECRET: ${BACKEND_SECRET}
    ports:
      - 7007:7007
      - 7008:7008

  postgres:
    image: postgres:12
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - backstage_pgdata:/var/lib/postgresql/data

volumes:
  backstage_pgdata:
